apiVersion: chistadata.io/v1
kind: ClusterSecret
metadata:
  name: secret-copy-synced
spec:
  includeNamespaces:
    - "apps*"
  valueFrom:
    secretName: secret-to-be-synced
    secretNamespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: secret-to-be-synced
  annotations:
    chistadata.io/name: secret-copy-synced
stringData:
  flux.yaml: |
    testProperty: null-value
  third-party.yaml: |
    tryAnotherProperty: value
