apiVersion: chistadata.io/v1
kind: ClusterSecret
metadata:
  name: secret-copy
spec:
  includeNamespaces:
    - "*"
  excludeNamespaces:
    - "kube*"
    - "default"
  valueFrom:
    secretNamespace: kube-system
    secretName: secret-to-be-copied
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: secret-to-be-copied
stringData:
  flux.yaml: |
    testProperty: null-value
  third-party.yaml: |
    tryAnotherProperty: value
