apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-secret.fullname" . }}-manager-role
  labels:
  {{- include "cluster-secret.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chistadata.io
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chistadata.io
  resources:
  - clustersecrets/finalizers
  verbs:
  - update
- apiGroups:
  - chistadata.io
  resources:
  - clustersecrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-secret.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-secrets
    app.kubernetes.io/part-of: cluster-secrets
  {{- include "cluster-secret.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-secret.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-secret.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'