apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-secret.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cluster-secrets
    app.kubernetes.io/part-of: cluster-secrets
    control-plane: controller-manager
  {{- include "cluster-secret.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "cluster-secret.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}